package com.example.firebase_ai

import com.google.firebase.ai.GenerativeModel
import com.google.firebase.ai.type.Content
import com.google.firebase.ai.type.FirebaseAIException
import kotlinx.serialization.KSerializer
import kotlinx.serialization.json.Json

/**
 * A type-safe wrapper around a GenerativeModel that is pre-configured
 * to return a specific data type [T].
 *
 * @param T The data type this model is configured to generate.
 * @property baseModel The underlying, pre-configured GenerativeModel instance.
 * @property serializer The KSerializer for the type [T].
 */
class TypedGenerativeModel<T : Any>(
    val baseModel: GenerativeModel,
    private val serializer: KSerializer<T>
) {
    /**
     * Generates new content from the input [Content] given to the model as a prompt.
     *
     * @param prompt The input(s) given to the model as a prompt.
     * @return The content generated by the model.
     * @throws [FirebaseAIException] if the request failed.
     * @see [FirebaseAIException] for types of errors.
     */
    suspend fun generateContent(
        prompt: Content,
        vararg prompts: Content
    ): TypedGenerateContentResponse<T> {
        val response = baseModel.generateContent(prompt, *prompts)

        // 2. Parse the JSON string from the response text.
        val parsedObject: T? = response.text?.let { jsonString ->
            try {
                Json.decodeFromString(serializer, jsonString)
            } catch (e: Exception) {
                e.printStackTrace()
                null
            }
        }

        // 3. Return the final wrapper object.
        return TypedGenerateContentResponse(
            typedContent = parsedObject,
            rawResponse = response
        )
    }

    /**
     * Generates new content from the input [Content] given to the model as a prompt.
     *
     * @param prompt The input(s) given to the model as a prompt.
     * @return The content generated by the model.
     * @throws [FirebaseAIException] if the request failed.
     * @see [FirebaseAIException] for types of errors.
     */
    public suspend fun generateContent(prompt: List<Content>): TypedGenerateContentResponse<T> {
        // 1. Call the underlying model. It's already configured to return the correct JSON.
        val response = baseModel.generateContent(prompt)

        // 2. Parse the JSON string from the response text.
        val parsedObject: T? = response.text?.let { jsonString ->
            try {
                Json.decodeFromString(serializer, jsonString)
            } catch (e: Exception) {
                e.printStackTrace()
                null
            }
        }

        // 3. Return the final wrapper object.
        return TypedGenerateContentResponse(
            typedContent = parsedObject,
            rawResponse = response
        )
    }

    /**
     * Generates content from a text prompt and parses it into the model's configured type [T].
     *
     * @param prompt The text prompt to send to the model.
     * @return A [TypedGenerateContentResponse] containing the parsed object and the raw response.
     */
    suspend fun generateContent(prompt: String): TypedGenerateContentResponse<T> {
        // 1. Call the underlying model. It's already configured to return the correct JSON.
        val response = baseModel.generateContent(prompt)

        // 2. Parse the JSON string from the response text.
        val parsedObject: T? = response.text?.let { jsonString ->
            try {
                Json.decodeFromString(serializer, jsonString)
            } catch (e: Exception) {
                e.printStackTrace()
                null
            }
        }

        // 3. Return the final wrapper object.
        return TypedGenerateContentResponse(
            typedContent = parsedObject,
            rawResponse = response
        )
    }
}