name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: |
          ./gradlew build